version: '2'
services:
  api:
    image: asermax/node-yarn
    links:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./api:/opt/app
    environment:
      - PORT=8000
      - MONGO_URL=mongodb://db:27017/tsuiseki
    command: sh -c "cd /opt/app && yarn start"
  frontend:
    image: asermax/node-yarn
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/opt/app
    command: sh -c "cd /opt/app && yarn start"
  db:
    image: mongo:3.4
    ports:
      - 27017:27017
